config/routes.rb
WebAppRails::Application.routes.draw do

  root :to => 'assignments#index'
  get 'login' => 'users#login'
  get 'logout' => 'sessions#destroy', as: :signout  

  get '/auth/github/callback', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')
  get '/signin' => redirect('/auth/github')

  post '/homeworks/rspec', to: 'homeworks#rspec'

  resources :plans
  resources :mockups
  resources :assignments

  
  

  

end

app/models/mockup.rb
# == Schema Information
#
# Table name: mockups
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class Mockup < ActiveRecord::Base
end

app/controllers/mockups_controller.rb
class MockupsController < ApplicationController
  before_action :set_mockup, only: [:show, :edit, :update, :destroy]

  # GET /mockups
  # GET /mockups.json
  def index
    @mockups = Mockup.all
  end

  # GET /mockups/1
  # GET /mockups/1.json
  def show
  end

  # GET /mockups/new
  def new
    @mockup = Mockup.new
  end

  # GET /mockups/1/edit
  def edit
  end

  # POST /mockups
  # POST /mockups.json
  def create
    @mockup = Mockup.new(mockup_params)

    respond_to do |format|
      if @mockup.save
        format.html { redirect_to @mockup, notice: 'Mockup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @mockup }
      else
        format.html { render action: 'new' }
        format.json { render json: @mockup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mockups/1
  # PATCH/PUT /mockups/1.json
  def update
    respond_to do |format|
      if @mockup.update(mockup_params)
        format.html { redirect_to @mockup, notice: 'Mockup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @mockup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mockups/1
  # DELETE /mockups/1.json
  def destroy
    @mockup.destroy
    respond_to do |format|
      format.html { redirect_to mockups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mockup
      @mockup = Mockup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mockup_params
      params[:mockup]
    end
end

app/helpers/mockups_helper.rb
module MockupsHelper
end

app/views/mockups/_form.html.erb
<%= form_for(@mockup) do |f| %>
  <% if @mockup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mockup.errors.count, "error") %> prohibited this mockup from being saved:</h2>

      <ul>
      <% @mockup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mockups/edit.html.erb
<h1>Editing mockup</h1>

<%= render 'form' %>

<%= link_to 'Show', @mockup %> |
<%= link_to 'Back', mockups_path %>

app/views/mockups/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th>Assignments</th>
          <th>Forks</th>
        </tr>
      </thead>
      <tbody>
        <tr><td><a href="#">Tic Tac Toe Sinatra</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Wookwoddle Rails Challenge</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Alien Sandwich Sinatra (LAB)</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Towers of Hanoi ORB (Todo)</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Recursive Recursorial</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">ABC Acme Systems Unlimited (Homework)</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
        <tr><td><a href="#">Repo Name</a></td><td><a href="#">GitHub</a></td></tr>
      </tbody>
    </table>
  </div>
</div>

app/views/mockups/new.html.erb
<h1>New mockup</h1>

<%= render 'form' %>

<%= link_to 'Back', mockups_path %>

app/views/mockups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_mockup_path(@mockup) %> |
<%= link_to 'Back', mockups_path %>