config/routes.rb
WebAppRails::Application.routes.draw do

  root :to => 'assignments#index'
  get 'login' => 'users#login'
  get 'logout' => 'sessions#destroy', as: :signout  

  get '/auth/github/callback', to: 'sessions#create'

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')
  get '/signin' => redirect('/auth/github')

  post '/homeworks/rspec', to: 'homeworks#rspec'

  resources :plans
  resources :mockups
  resources :assignments

  
  

  

end

app/models/assignment.rb
# == Schema Information
#
# Table name: assignments
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  full_name           :string(255)
#  web_url             :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  description         :string(255)
#  post_date           :datetime
#  due_date            :datetime
#  evaluation_type     :string(255)
#  branch              :string(255)
#  github_created_at   :string(255)
#  instructor_gravatar :string(255)
#  instructor_profile  :string(255)
#  instructor          :string(255)
#  spec_present        :boolean          default(FALSE)
#

class Assignment < ActiveRecord::Base
  belongs_to :student
  belongs_to :user
  has_many :homeworks
  has_many :students, through: :homeworks

  acts_as_taggable

  # IN RAKE ASSIGNMENTS
  # Assignment.all => clone
  # parse readmes
  # update database and cleanup

  DEFAULT_GENERATE_TAGS_LIST = ["todo", "lab", "homework", "quiz", "rails", "sinatra", "rack", "git"]

  def self.initial_generate_tags
    assignments = Assignment.all
    clone_all(assignments)
    assignments.each { |a| generate_tags(a) }
    sleep 10
    assignments.each { |a| FileUtils.rm_r(a.repo_path) }
  end

  def self.clone_all(assignments)
    assignments.each do |asst|
      asst.clone
    end
    puts "System is cloning. Wait three minutes."
    sleep 180
  end

  def clone
    puts "  Cloning #{self.name}... "
    system(cloner)
  end

  def cloner
    "bash bin/cloner.sh %s %s &> /dev/null &" % [self.name, self.url]
  end

  def url
    clone_url
  end

  def repo_path
    "tmp/#{self.name}"
  end

  def fork_url
    self.web_url + "/fork"
  end

  def graded_homework_of(student_obj)
    hw = Homework.where(:student_id => student_obj.id).where(:assignment_id => self.id)
    if hw
      hw = hw.first
      if hw.examples
        if hw.examples > 0
          return hw
        end
      end
    end
    return nil
  end

  def self.generate_tags(assignment)
    tags_array = tags_from_readme(assignment)
    tags_array << DEFAULT_GENERATE_TAGS_LIST.select {|tag| assignment.full_name.include?(tag) && !tags_array.include?(tag) }
    tags_array.flatten!
    assignment.tag_list.add(tags_array)
    assignment.save
  end

  def self.tags_from_readme(assignment)
    tags = []
    file = File.open("#{assignment.repo_path}/README.md")
      file.each_line do |line|
        unless line.match(/^tags: ([\S ]+)/).nil?
          tags = line.match(/^tags: ([\S ]+)/)[1]
        end
      end
    tags.split(", ")
    rescue
      puts "  No readme for #{assignment.name}"
      tags
  end

  def branch
    "master" # see Homework.rb grader_command
  end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @student = Student.find_by(:name => current_user.login)
    @assignments = Assignment.all.order('github_created_at DESC')
    Homework.get_most_recent_issue(session[:token], current_user) if session[:token]
    @plan = Plan.last
    if @plan
      @percent = ((@plan.day_number.to_f/60).to_f)*100
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @assignment }
      else
        format.html { render action: 'new' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:title, :url)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_fork_button.html.erb
<!-- <span class="status">Not Forked &raquo;</span>  --><a href="<%= fork_assignment %>" class="btn btn-default btn-xs" role="button">Fork</a>

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/_progress_bar.html.erb
        <div class="progress">
          <div class="progress-bar progress-bar-success" style="width: <%= test_scores[:passing] %>">
          </div>
          <div class="progress-bar progress-bar-warning" style="width: <%= test_scores[:pending] %>">
          </div>
          <div class="progress-bar progress-bar-danger" style="width: <%= test_scores[:failing] %>">
          </div>
        </div>

app/views/assignments/edit.html.erb
<h1>Editing assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<div class="row">
  <div class="col-md-8  timeline-column">
    <div class="time-line">
      <div class="plan-4-day">
        <% if @plan %>
          <h2>Plan for Day <%= @plan.day_number %>:</h2> <p><%= @plan.content %> </p>
          <div class="course-timeline">
            <div class="progress">
              <div class="progress-bar" style="width: <%= @percent %>%">
                <span class="day">Day: <%= @plan.day_number %></span>
              </div>
            </div>
          </div>
        <% else %>
          <h2>Plan for the day: No Plan. Do whatever.</h2>
        <% end %>
      </div>
    </div>
  </div><!-- end col 1 -->
  <div class="col-md-4  equal-height"> 
    <div class="feed equal-height">
    <h2>Live from Github...</h2>
      <% GithubFeed.get_feed.each do |entry| %>
       <p><a href="<%= entry.url %>" title=""><%= entry.title[0..60] %>...</a></p>
      <% end %>
    </div>
  </div><!-- end col 2 -->
</div>

<div class="row table-top-padding">
  <div class="col-lg-12">
    <table class="table table-striped assignments-list">
        <thead>
          <tr>
            <th width="15">Rspec</th>
            <th width="165">Assignment</th>
            <th width="100">Progress</th>
            <th width="234">Issues<!-- Issues <span class="glyphicon glyphicon-comment"></span>--></th>
          </tr>
        </thead>
        <tbody>
          <% @student.assignments.each_with_index do |assignment,i| %>
          <tr>
            <td width="15">
              <% if assignment.spec_present %>
                <%= form_tag '/homeworks/rspec' do %>
                <input name="assignment_id" value="<%= assignment.id %>" type="hidden" />
                <input name="student_id" value="<%= @student.id %>" type="hidden" />
                <button type="submit" class="btn btn-default btn-xs"><span class="icon-bar-chart"></span></button>
                  <% end %>
              <% else %>
              <p class="empty-cell">--</p>
              <% end %>
            </td>
            <td width="165"><h2><%= link_to assignment.name, assignment.web_url %></h2>
              <ul class="meta-info">
                <% unless assignment.tags.empty? %>
                <% assignment.tags.each do |tag| %>
                <li><span class="label label-default">
                  <span class="glyphicon glyphicon-tag"></span>&nbsp;<a href="#" title=""><%= tag.name %></a></span>
                </li>
                <% end %>
                <% end %>

              </ul>
            </td>
            <td>
              <% hw = assignment.graded_homework_of(@student) %>
              <% if hw %>
              <%= render partial: "progress_bar", locals: {test_scores: hw.rspec_score} %>
              <% else %>
              <%= render partial: "fork_button", locals: {fork_assignment: assignment.fork_url} %>
              <% end %>
        </td>
        <td class="issues">
          <% @homework = Homework.where("assignment_id = ? AND student_id = ?", assignment.id, @student.id).first %>
          <p><%= @homework.current_issue %> <button type="button" class="btn btn-default btn-xs">New Issue</button> 
          <!-- <a href="#" class="btn btn-default btn-xs" role="button">New Issue</a> --></p>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div> <!-- col-lg-12 -->
</div> <!-- row table-top-padding -->

app/views/assignments/new.html.erb
<h1>New assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @assignment.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @assignment.url %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>